<?php
// Require composer autoload
require_once APP_PATH . '../../vendor/autoload.php';

use Mpdf\Mpdf;
use Mpdf\HTMLParserMode;
use Mpdf\Output\Destination;

//Activa el almacenamiento en búfer de la salida
ob_start();

?>
<html>
    <head>
        <style type="text/css">
            @page {
                background-color:#ffffff;
                header: html_myHeader1;
                footer: html_myFooter1;
            }
        </style> 	

    </head>
    <body>
        <htmlpageheader name="myHeader1">
            <div style="text-align: center; font-weight: bold"><?= isset($title) ? $title : 'Report' ?></div>
        </htmlpageheader>

        <?php View::content(); ?>

        <htmlpagefooter name="myFooter1">
            <table width="100%" style="border-top: 1px dotted grey; vertical-align: bottom; font-family: serif; font-size: 8pt;  color: #000000; font-style: italic;">
                <tr>
                    <td width="33%"><span style="font-style: italic;">{DATE d/m/Y}</span></td>
                    <td width="33%" align="center" style="font-weight: bold; font-style: italic;"></td>
                    <td width="33%" style="text-align: right; ">{PAGENO}/{nbpg}</td>
                </tr>
            </table>
        </htmlpagefooter>
    </body>
</html>
<?php
$html = ob_get_clean();
ob_clean();

// Crea una instancia de la clase y le pasa el directorio temporal
$mpdf = new Mpdf(['tempDir' => APP_PATH . '/temp']);

// Carga el CSS externo
$stylesheet = file_get_contents('./css/pdf.min.css');
$mpdf->WriteHTML($stylesheet, HTMLParserMode::HEADER_CSS);
// Escribe el contenido HTML (Template + View):
$mpdf->WriteHTML($html);

// Título por defecto
if (! isset($fileName)) {
    $fileName = 'Report';
}
// Obliga la descarga del PDF
$mpdf->Output("$fileName.pdf", Destination::DOWNLOAD);
